step_1_exceptions:
  ΦΑΓΙΑ: ΦΑ
  ΦΑΓΙΟΥ: ΦΑ
  ΦΑΓΙΩΝ: ΦΑ
  ΣΚΑΓΙΑ: ΣΚΑ
  ΣΚΑΓΙΟΥ: ΣΚΑ
  ΣΚΑΓΙΩΝ: ΣΚΑ
  ΟΛΟΓΙΟΥ: ΟΛΟ
  ΟΛΟΓΙΑ: ΟΛΟ
  ΟΛΟΓΙΩΝ: ΟΛΟ
  ΣΟΓΙΟΥ: ΣΟ
  ΣΟΓΙΑ: ΣΟ
  ΣΟΓΙΩΝ: ΣΟ
  ΤΑΤΟΓΙΑ: ΤΑΤΟ
  ΤΑΤΟΓΙΟΥ: ΤΑΤΟ
  ΤΑΤΟΓΙΩΝ: ΤΑΤΟ
  ΚΡΕΑΣ: ΚΡΕ
  ΚΡΕΑΤΟΣ: ΚΡΕ
  ΚΡΕΑΤΑ: ΚΡΕ
  ΚΡΕΑΤΩΝ: ΚΡΕ
  ΠΕΡΑΣ: ΠΕΡ
  ΠΕΡΑΤΟΣ: ΠΕΡ
  ΠΕΡΑΤΑ: ΠΕΡ
  ΠΕΡΑΤΩΝ: ΠΕΡ
  ΤΕΡΑΣ: ΤΕΡ
  ΤΕΡΑΤΟΣ: ΤΕΡ
  ΤΕΡΑΤΑ: ΤΕΡ
  ΤΕΡΑΤΩΝ: ΤΕΡ
  ΦΩΣ: ΦΩ
  ΦΩΤΟΣ: ΦΩ
  ΦΩΤΑ: ΦΩ
  ΦΩΤΩΝ: ΦΩ
  ΚΑΘΕΣΤΩΣ: ΚΑΘΕΣΤ
  ΚΑΘΕΣΤΩΤΟΣ: ΚΑΘΕΣΤ
  ΚΑΘΕΣΤΩΤΑ: ΚΑΘΕΣΤ
  ΚΑΘΕΣΤΩΤΩΝ: ΚΑΘΕΣΤ
  ΓΕΓΟΝΟΣ: ΓΕΓΟΝ
  ΓΕΓΟΝΟΤΟΣ: ΓΕΓΟΝ
  ΓΕΓΟΝΟΤΑ: ΓΕΓΟΝ
  ΓΕΓΟΝΟΤΩΝ: ΓΕΓΟΝ